// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nomade.domain;

import com.nomade.domain.Confidentiality;
import com.nomade.domain.SubTopic;
import com.nomade.domain.SubTopicDataOnDemand;
import com.nomade.domain.Topic;
import com.nomade.domain.TopicDataOnDemand;
import com.nomade.domain.UserNomade;
import com.nomade.service.SubTopicService;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SubTopicDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SubTopicDataOnDemand: @Component;
    
    private Random SubTopicDataOnDemand.rnd = new SecureRandom();
    
    private List<SubTopic> SubTopicDataOnDemand.data;
    
    @Autowired
    TopicDataOnDemand SubTopicDataOnDemand.topicDataOnDemand;
    
    @Autowired
    SubTopicService SubTopicDataOnDemand.subTopicService;
    
    public SubTopic SubTopicDataOnDemand.getNewTransientSubTopic(int index) {
        SubTopic obj = new SubTopic();
        setConfidentiality(obj, index);
        setContent(obj, index);
        setCreated(obj, index);
        setNomade(obj, index);
        setParentTopic(obj, index);
        setSubTopics(obj, index);
        setTitle(obj, index);
        return obj;
    }
    
    public void SubTopicDataOnDemand.setConfidentiality(SubTopic obj, int index) {
        Confidentiality confidentiality = Confidentiality.class.getEnumConstants()[0];
        obj.setConfidentiality(confidentiality);
    }
    
    public void SubTopicDataOnDemand.setContent(SubTopic obj, int index) {
        String content = "content_" + index;
        obj.setContent(content);
    }
    
    public void SubTopicDataOnDemand.setCreated(SubTopic obj, int index) {
        Date created = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreated(created);
    }
    
    public void SubTopicDataOnDemand.setNomade(SubTopic obj, int index) {
        UserNomade nomade = null;
        obj.setNomade(nomade);
    }
    
    public void SubTopicDataOnDemand.setParentTopic(SubTopic obj, int index) {
        Topic parentTopic = topicDataOnDemand.getRandomTopic();
        obj.setParentTopic(parentTopic);
    }
    
    public void SubTopicDataOnDemand.setSubTopics(SubTopic obj, int index) {
        SubTopic subTopics = obj;
        obj.setSubTopics(subTopics);
    }
    
    public void SubTopicDataOnDemand.setTitle(SubTopic obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public SubTopic SubTopicDataOnDemand.getSpecificSubTopic(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SubTopic obj = data.get(index);
        BigInteger id = obj.getId();
        return subTopicService.findSubTopic(id);
    }
    
    public SubTopic SubTopicDataOnDemand.getRandomSubTopic() {
        init();
        SubTopic obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return subTopicService.findSubTopic(id);
    }
    
    public boolean SubTopicDataOnDemand.modifySubTopic(SubTopic obj) {
        return false;
    }
    
    public void SubTopicDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = subTopicService.findSubTopicEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SubTopic' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SubTopic>();
        for (int i = 0; i < 10; i++) {
            SubTopic obj = getNewTransientSubTopic(i);
            try {
                subTopicService.saveSubTopic(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
