// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nomade.domain;

import com.nomade.domain.SubTopicDataOnDemand;
import com.nomade.domain.SubTopicIntegrationTest;
import com.nomade.service.SubTopicService;
import java.math.BigInteger;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect SubTopicIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SubTopicIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SubTopicIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    SubTopicDataOnDemand SubTopicIntegrationTest.dod;
    
    @Autowired
    SubTopicService SubTopicIntegrationTest.subTopicService;
    
    @Test
    public void SubTopicIntegrationTest.testCountAllSubTopics() {
        Assert.assertNotNull("Data on demand for 'SubTopic' failed to initialize correctly", dod.getRandomSubTopic());
        long count = subTopicService.countAllSubTopics();
        Assert.assertTrue("Counter for 'SubTopic' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SubTopicIntegrationTest.testFindSubTopic() {
        SubTopic obj = dod.getRandomSubTopic();
        Assert.assertNotNull("Data on demand for 'SubTopic' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SubTopic' failed to provide an identifier", id);
        obj = subTopicService.findSubTopic(id);
        Assert.assertNotNull("Find method for 'SubTopic' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SubTopic' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SubTopicIntegrationTest.testFindAllSubTopics() {
        Assert.assertNotNull("Data on demand for 'SubTopic' failed to initialize correctly", dod.getRandomSubTopic());
        long count = subTopicService.countAllSubTopics();
        Assert.assertTrue("Too expensive to perform a find all test for 'SubTopic', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SubTopic> result = subTopicService.findAllSubTopics();
        Assert.assertNotNull("Find all method for 'SubTopic' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SubTopic' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SubTopicIntegrationTest.testFindSubTopicEntries() {
        Assert.assertNotNull("Data on demand for 'SubTopic' failed to initialize correctly", dod.getRandomSubTopic());
        long count = subTopicService.countAllSubTopics();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SubTopic> result = subTopicService.findSubTopicEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SubTopic' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SubTopic' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SubTopicIntegrationTest.testSaveSubTopic() {
        Assert.assertNotNull("Data on demand for 'SubTopic' failed to initialize correctly", dod.getRandomSubTopic());
        SubTopic obj = dod.getNewTransientSubTopic(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SubTopic' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SubTopic' identifier to be null", obj.getId());
        try {
            subTopicService.saveSubTopic(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        Assert.assertNotNull("Expected 'SubTopic' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SubTopicIntegrationTest.testDeleteSubTopic() {
        SubTopic obj = dod.getRandomSubTopic();
        Assert.assertNotNull("Data on demand for 'SubTopic' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SubTopic' failed to provide an identifier", id);
        obj = subTopicService.findSubTopic(id);
        subTopicService.deleteSubTopic(obj);
        Assert.assertNull("Failed to remove 'SubTopic' with identifier '" + id + "'", subTopicService.findSubTopic(id));
    }
    
}
