// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nomade.domain;

import com.nomade.domain.TopicIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TopicIntegrationTest_Roo_Configurable {
    
    declare @type: TopicIntegrationTest: @Configurable;
    
}
