// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nomade.domain;

import com.nomade.domain.BeanNewItineraire;
import java.io.Serializable;

privileged aspect BeanNewItineraire_Roo_Serializable {
    
    declare parents: BeanNewItineraire implements Serializable;
    
    private static final long BeanNewItineraire.serialVersionUID = 1L;
    
}
