// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nomade.domain;

import com.nomade.domain.BeanPasswordReset;
import java.io.Serializable;

privileged aspect BeanPasswordReset_Roo_Serializable {
    
    declare parents: BeanPasswordReset implements Serializable;
    
    private static final long BeanPasswordReset.serialVersionUID = 1L;
    
}
