// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nomade.domain;

import com.nomade.domain.File;

privileged aspect File_Roo_JavaBean {
    
    public String File.getFileName() {
        return this.fileName;
    }
    
    public void File.setFileName(String fileName) {
        this.fileName = fileName;
    }
    
}
