// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nomade.domain;

import com.nomade.domain.Etape;
import com.nomade.domain.Point;

privileged aspect Point_Roo_JavaBean {
    
    public Etape Point.getPoint() {
        return this.point;
    }
    
    public void Point.setPoint(Etape point) {
        this.point = point;
    }
    
}
